### ISSUE TITLE
loading js9support.js using ipython publish_display_data gives errors

### ISSUE THREAD

**Issue by gijzelaerr** [gijzelaerr/js9notebook#1]
Trying to inject `js9support.js` into a running notebook using `IPython.core.displaypub.publish_display_data()` gives:

```
TypeError: Cannot read property 'plugins' of undefined
```

`publish_display_data()` ships the JSON encoded javascript to the browser, where it is executed using javascript `eval()`. When I try to load the individual components of which js9support is composed I discovered that the following support files are problematic:
- **js/flot-zoom.min.js**: `TypeError: Cannot read property 'plugins' of undefined`
- **js/fabric.min.js**: `TypeError: Cannot read property 'object' of undefined`

**Comment by montefra** [comment]
@gijzelaerr: it makes sense to move it here. Thanks

**Comment by ericmandel** [comment]
@gijzelaerr If you load js/flot-zoom.js and js/fabric.js instead of the min file, do you still get the error?

Also ... you might want to set up an independent test by doing an xhr (or $.ajax) of these files and then an eval() of the retrieved result. Just simple JavaScript , no need for iPython, and it would tell you if iPython is doing something odd or if there really is a problem with the files. (I'm traveling until Monday or I would do this now ... also, comments will be sporadic until then.)

**Comment by gijzelaerr** [comment]
Yes, also the non minified versions give the same errors.

I'll dust of my javascript knowledge that got a bit rusty.

**Comment by gijzelaerr** [comment]
Yes, seeing the same error there so it is unrelated to Python:
```
var xhttp = new XMLHttpRequest();
xhttp.open("GET", "js/flot-zoom.js", true);
xhttp.send();
var x = xhttp.responseText;
eval(x);
VM431:91 Uncaught TypeError: Cannot read property 'plugins' of undefined(…)(anonymous function) @ VM431:91(anonymous function) @ VM431:92(anonymous function) @ VM430:2InjectedScript._evaluateOn @ VM89:904InjectedScript._evaluateAndWrap @ VM89:837InjectedScript.evaluate @ VM89:693
```

**Comment by gijzelaerr** [comment]
Actually, I should load the dependencies first, of course. 

This does not give the error.
```
var scripts = [
  "js/jquery.min.js",
  "js/jquery.contextMenu.min.js",
  "js/jquery.flot.js",
  "js/jquery.flot.errorbars.min.js",
  "js/jquery.flot.selection.min.js",
  "js/flot-zoom.min.js"
];

var xhttp, script, x;
for (var i in scripts) {
    script = scripts[i]
    xhttp = new XMLHttpRequest();
    xhttp.open("GET",script, true);
    xhttp.send();
    var x = xhttp.responseText;
    eval(x);
}
```

**Comment by gijzelaerr** [comment]
Ok so when I load the javascript manually with xhr, `eval` fails on `flot-zoom.js` again, but with a different error: `Uncaught ReferenceError: $ is not defined`. The chrome integrated debugger shows the actual point of failure using xhr now: https://github.com/ericmandel/js9/blob/master/js/flot-zoom.js#L92

I did load jquery though. Will keep digging.

**Comment by gijzelaerr** [comment]
Sorry, posted some noise, made same mistakes with the xhr request. I wrote this script:
https://gist.github.com/gijzelaerr/ba3b30685022f0766cab

`js/flot-zoom.min.js` loads correctly now, but `js/fabric.min.js` fails with the same error, but now I can find out where it fails: https://github.com/ericmandel/js9/blob/master/js/fabric-v1.4.11.js#L2696

**Comment by ericmandel** [comment]
You might try the latest version of fabric.js ... and if it works, I'll upgrade (which will be painful but we'll do it). I get into this when I get back ...

**Comment by gijzelaerr** [comment]
fabric 1.5.0 has the same problem. I'll report it upstream, see what they have to say.

**Comment by gijzelaerr** [comment]
https://groups.google.com/forum/#!topic/fabricjs/W09fEtKopkk

**Comment by gijzelaerr** [comment]
this issue seems to be related:

http://stackoverflow.com/questions/4670805/javascript-eval-on-global-scope

using `$.globaleval()` works:

http://api.jquery.com/jQuery.globalEval/

**Comment by ericmandel** [comment]
There are three possible solutions:
1. The jupyter developers change from simple eval() to something more robust (assuming that is the problem)
2. The fabric developers modify fabric to avoid the problem 
3. I wrap the fabric code in something that avoids the problem, which can be done while generating js9support.js

I'll look into the third option on Monday when I get back.

**Comment by gijzelaerr** [comment]
Nicholas Bollweg wrote a very useful response on the IPython development list:

https://mail.scipy.org/pipermail/ipython-dev/2015-October/016892.html

**Comment by gijzelaerr** [comment]
@ericmandel I get the idea that JS9 is trying to download various files dynamically from the location where it is imported from. It looks like that is not working properly (error: "could not read JS9 data") if it is not running on the same domain:

https://github.com/ericmandel/js9/blob/master/js9.js#L636

 The other 2 errors described by Nicholas are not a show stopper afaik.

I think it would be very useful for JS9 to be able to be served directly from a remote webserver, also from a CDN. Is it possible to compile everything in just one big javascript file?

**Comment by ericmandel** [comment]
> error: "could not read JS9 data")

Yes, that error almost certainly is a same-origin error. But no matter: I don't think  we want to preload any files for the iPython version. Instead we'll use a special web page that will display exactly the JS9 components that want to display. For example, we could make a web page that shows only the menubar and JS9 display, which would look like [this page](http://js9.si.edu/js9/js9basics.html)  ... but without the loadable URLs and demos. Or we could get fancier and show some of the more standard DS9 GUI elements, like the right-hand side of [this page](http://js9.si.edu/js9/js9panzoom.html). This is just a matter of deciding what we want on the web page. I recommend using the [js9basics](http://js9.si.edu/js9/js9basics.html) for initial testing.

> CDN. Is it possible to compile everything in just one big javascript file?

I'm sure we can copy all of JS9 into one big file for a CDN load (although we at Smithsonian are prohibited from usng CDN!). I don't to that by default:
1. I hope that someday the js9support will stabilize and won't have to be reloaded with each release.
2. it's unclear whether Web designers always want to load the plugins.
3. using CDN precludes site configuration via js9Prefs and won't conne cto to a back-end server

But for the iPython version, we will simply decide what we want to include and do it. I'll play with a single file to load today and let you know if there are issues. But #3 might be important: lack of connection to a back-end helper will limit JS9 functionality somewhat (see below).

> inability to connect to socket.io, which is unsurprising

I don't understand why this would fail and it would be very good to make it work. In the upcoming v1.6, you will be able to use js9.si.edu as a proxy staging area in order to be able to load any FITS URL from the Web into any JS9 display (while avoiding same-origin issues). But you have to be able to make that connection to the JS9 helper via socket.io.

> JS9 prefs file not available: js9Prefs.json

Not a real problem: the dynamic loading of js9Prefs.json is so that sites can override the default parameters in JS9. For example, "linear" scale is the default but X-ray sites will almost certainly want to use the "log" scale by default. We don't need to use js9Prefs for iPython, although again, I don't understand why it does not work. If the error itself is a problem, I can arrange a way to let JS9 know **not** to try to load the prefs files.

**Comment by ericmandel** [comment]
I've added a cdn rule to the JS9 Makefile to generate js9-v$(VERSION).css and js9-v$(VERSION).js files for use with CDN.  It just uses cat and the resulting files works as expected.

**Comment by ericmandel** [comment]
@gijzelaerr I pushed a number of mods to JS9 to ensure that using the (newly renamed) js9-allinone.css and js9-allinone.js files works properly (e.g. double-click region actually brings up the region edit window, light windows have buttons with images, etc.) and deals gracefully with the inherent limitations (no server-side analysis, no help files, etc). I don't know if we will ever use this via CDN, but it does work well.

**Comment by gijzelaerr** [comment]
O whow, that is great! You people may not use it over a CDN, but I'm quite sure a lot of other people want to use it this way.

I must say I'm very busy at the moment and will go for a holiday on Monday, so I won't have a lot of time to look at this at the moment, but will do for sure in November.

thanks!

**Comment by ericmandel** [comment]
There is now a semi-stable jupyter folder on the js9 web site that you can use:

```
%%html
<div class="JS9Menubar"></div>
<div class="JS9"></div>
<link type="text/css" rel="stylesheet" href="//js9.si.edu/jupyter/js9-allinone.css">
<script type="text/javascript" src="//js9.si.edu/jupyter/js9-allinone.js"></script>
```

The allinone files are links to the "current" version. Previous version still exist, so you can load them as well. (The new version, by the way, supports dynamic resize of the JS9 display using a grab handle in the lower right corner).

Everything seems to work except the dialog boxes into which you type, e.g. you cannot set the zoom or clipping values from the menus. I searched the jupyter documentation and did not see how to focus the keyboard on the HTML output, instead of the edit/command focus that jupyter offers. Do you know how to deal with this? Otherwise, should we be disabling all of these dialog boxes? I'd hate to do that, but typing into one completely breaks JS9 in jupyter.

**Comment by gijzelaerr** [comment]
great work Eric! Some people are already using this now here. I'm too busy again now, but when I find the time I'll try and work on integrating more with jupyter (widgets).

**Comment by ericmandel** [comment]
With crucial help from Nicholas Bollweg, I fixed the keyboard input to menus and dialog boxes in Jupyter/JS9.

**Comment by gijzelaerr** [comment]
great work! 

Maybe we should close this issue? since the original issue has nothing to do anymore with the current discussion. This makes future reference much easier.
